# Generated by Django 5.1.1 on 2024-09-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (-2, "awful"),
                            (-1, "bad"),
                            (0, "fine"),
                            (1, "good"),
                            (2, "amazing"),
                        ]
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
