# Generated by Django 5.1.1 on 2024-10-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_moodentry_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateField(),
        ),
    ]
